# Generated by Django 5.0.6 on 2024-06-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0003_myauthentication_delete_authenticate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myauthentication',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='myauthentication',
            old_name='passowrd',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='myauthentication',
            old_name='user_name',
            new_name='Username',
        ),
    ]
