# Generated by Django 5.0.6 on 2024-06-15 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0004_rename_email_myauthentication_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myauthentication',
            name='Email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
